Adding Logical layout implementation
andrewdavidmackenzie/pigg pull request #56
Opened 2024-05-24 14:31 UTC by sundaram123krishnan

Fixes #42

2024-05-24 18:23 UTC, andrewdavidmackenzie requested changes
I need to study the UI code more and dive into that area more in the next few days, then maybe will suggest some refactors..... for now, just some minor comments in the review.

2024-05-25 06:53 UTC, sundaram123krishnan commented on src/pin_layout.rs
> +            &Layout::ALL[..],
yes, the slice type implements Borrow trait

2024-05-25 06:55 UTC, sundaram123krishnan commented on src/piggui.rs
> +        size: iced::Size::new(800.0, 1000.0),
Default size doesn't fit the logical layout, that's why increased the height

2024-05-25 08:50 UTC, andrewdavidmackenzie commented on src/piggui.rs
> +        size: iced::Size::new(800.0, 1000.0),
OK. Maybe later we can figure out how to have Iced grow the size to "wrap" the contents, so it's flexible.
But not urgent.

2024-05-25 15:55 UTC, andrewdavidmackenzie approved these changes

2024-05-25 16:06 UTC, merged